theme: jekyll-theme-cayman
<a href="https://github.com/Shh6266/Shh6266.github.io/blob/main/main.py" download="Ncov_Main">点击下载</a>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
	</head>
	<body>
		 <a href="https://github.com/Shh6266/Shh6266.github.io/blob/main/main.py" download="Ncov_Main">点击下载</a>

	</body>
</html>
